"""
Performance Report Generator
=============================
Generates a human-readable Markdown performance report from benchmark
results and device info. Useful for README output and GitHub uploads.

Usage:
    from optimizer.utils.report import generate_report
    report = generate_report(results, device_info, output_path="report.md")
"""

import os
from datetime import datetime
from typing import List, Optional, Dict, Any
from optimizer.utils.logger import get_logger

logger = get_logger(__name__)


def generate_report(
    results: List[Any],          # List[BenchmarkResult]
    device_info: Optional[Dict[str, Any]] = None,
    output_path: Optional[str] = None,
    title: str = "OpenCL AI Inference Optimizer — Performance Report",
) -> str:
    """
    Generate a Markdown performance report.

    Args:
        results     : List of BenchmarkResult objects.
        device_info : Dict from OpenCLDevice.device_info() (optional).
        output_path : If given, save the report to this .md file.
        title       : Report title string.

    Returns:
        The report as a Markdown string.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        f"# {title}",
        f"",
        f"**Generated:** {now}",
        f"",
    ]

    # ------------------------------------------------------------------
    # Device section
    # ------------------------------------------------------------------
    if device_info:
        lines += [
            "## 🖥️ Device Information",
            "",
            "| Property | Value |",
            "|---|---|",
        ]
        field_map = {
            "platform":         "Platform",
            "device":           "Device Name",
            "type":             "Device Type",
            "compute_units":    "Compute Units",
            "max_freq_mhz":     "Max Frequency (MHz)",
            "global_mem_mb":    "Global Memory (MB)",
            "local_mem_kb":     "Local Memory (KB)",
            "max_work_group_size": "Max Work Group Size",
        }
        for key, label in field_map.items():
            if key in device_info:
                lines.append(f"| {label} | {device_info[key]} |")
        lines.append("")

    # ------------------------------------------------------------------
    # Results table
    # ------------------------------------------------------------------
    if results:
        lines += [
            "## 📊 Benchmark Results",
            "",
            "| Benchmark | CPU Mean (ms) | OpenCL Mean (ms) | Speedup | Winner |",
            "|---|---|---|---|---|",
        ]
        for r in results:
            winner_icon = "🚀 OpenCL" if r.winner == "OpenCL" else "💻 CPU"
            lines.append(
                f"| {r.label} "
                f"| {r.cpu.mean_ms:.3f} "
                f"| {r.gpu.mean_ms:.3f} "
                f"| **{r.speedup:.2f}x** "
                f"| {winner_icon} |"
            )
        lines.append("")

        # -- Detailed breakdown per benchmark --
        lines += ["## 📋 Detailed Results", ""]
        for r in results:
            lines += [
                f"### {r.label}",
                "",
                f"- **Runs:** {r.runs}  |  **Warm-up:** {r.warmup_runs}",
                f"- **Speedup:** {r.speedup:.2f}x  → winner: **{r.winner}**",
                "",
                "| Metric | CPU (NumPy) | OpenCL |",
                "|---|---|---|",
                f"| Mean (ms) | {r.cpu.mean_ms:.3f} | {r.gpu.mean_ms:.3f} |",
                f"| Std  (ms) | {r.cpu.std_ms:.3f}  | {r.gpu.std_ms:.3f}  |",
                f"| Min  (ms) | {r.cpu.min_ms:.3f}  | {r.gpu.min_ms:.3f}  |",
                f"| Max  (ms) | {r.cpu.max_ms:.3f}  | {r.gpu.max_ms:.3f}  |",
                f"| Calls/sec | {r.cpu.throughput:.1f} | {r.gpu.throughput:.1f} |",
                "",
            ]

    # ------------------------------------------------------------------
    # Footer
    # ------------------------------------------------------------------
    lines += [
        "---",
        "",
        "> Report generated by **OpenCL AI Inference Optimizer** v1.0.0  ",
        "> https://github.com/your-org/opencl-ai-optimizer",
        "",
    ]

    report = "\n".join(lines)

    if output_path:
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(report)
        logger.info(f"Performance report saved to: {output_path}")

    return report
